require "nice_assets/abstract_interface.rb"

require "nice_assets/asset_specification.rb"
require "nice_assets/asset_roster.rb"
require "nice_assets/asset_workflow.rb"

# require "nice_assets/asset.rb"
# require "nice_assets/asset_seeker.rb"
# require "nice_assets/asset_manager.rb"
# require "nice_assets/fluid.rb"
# require "nice_assets/active_workflow.rb"
# require "nice_assets/workflow.rb"
# require "nice_assets/builders/active_fluid.rb"
# require "nice_assets/builders/active_workflow_builder.rb"
# require "nice_assets/builders/active_workflow_reader.rb"
# require "nice_assets/cascadable.rb"
# require "nice_assets/cascade.rb"
